// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define actAbout 20 
#define actAbout_LabelTitle_RESID 2
#define actAbout_TooltipTitle_RESID 3
#define actAjustements 24 
#define actAjustements_LabelTitle_RESID 4
#define actBdd 36 
#define actBdd_LabelTitle_RESID 60001
#define actBdd_SmallImages_RESID 60002
#define actBdd_LargeImages_RESID 60003
#define actBddMaj 38 
#define actBddMaj_LabelTitle_RESID 60004
#define actBddMaj_SmallImages_RESID 60005
#define actBddMaj_LargeImages_RESID 60006
#define actBddNew 37 
#define actBddNew_LabelTitle_RESID 60007
#define actBddNew_SmallImages_RESID 60008
#define actBddNew_LargeImages_RESID 60009
#define actBddSQL 39 
#define actBddSQL_LabelTitle_RESID 60010
#define actBddSQL_SmallImages_RESID 60011
#define actBddSQL_LargeImages_RESID 60012
#define actCategories 26 
#define actCategories_LabelTitle_RESID 5
#define actCategories_TooltipTitle_RESID 6
#define actCategories_TooltipDescription_RESID 7
#define actCategories_SmallImages_RESID 8
#define actCategories_LargeImages_RESID 9
#define actChangeUser 10 
#define actChangeUser_LabelTitle_RESID 10
#define actChangeUser_SmallImages_RESID 11
#define actChangeUser_LargeImages_RESID 12
#define actConditionnements 21 
#define actConditionnements_LabelTitle_RESID 13
#define actConditionnements_TooltipTitle_RESID 14
#define actConditionnements_TooltipDescription_RESID 15
#define actConditionnements_SmallImages_RESID 16
#define actConditionnements_LargeImages_RESID 17
#define actExportStd 3 
#define actExportStd_LabelTitle_RESID 18
#define actExportStd_SmallImages_RESID 19
#define actExportStd_LargeImages_RESID 20
#define actFrequences 29 
#define actFrequences_LabelTitle_RESID 21
#define actFrequences_TooltipTitle_RESID 22
#define actFrequences_SmallImages_RESID 23
#define actFrequences_LargeImages_RESID 24
#define actGroupes 22 
#define actGroupes_LabelTitle_RESID 25
#define actGroupes_TooltipTitle_RESID 26
#define actGroupes_TooltipDescription_RESID 27
#define actGroupes_SmallImages_RESID 28
#define actGroupes_LargeImages_RESID 29
#define actGroupesSites 27 
#define actGroupesSites_LabelTitle_RESID 30
#define actGroupesSites_TooltipTitle_RESID 31
#define actGroupesSites_SmallImages_RESID 32
#define actGroupesSites_LargeImages_RESID 33
#define actImportStd 2 
#define actImportStd_LabelTitle_RESID 34
#define actImportStd_SmallImages_RESID 35
#define actImportStd_LargeImages_RESID 36
#define actOpenArchive 11 
#define actOpenArchive_LabelTitle_RESID 37
#define actOpenArchive_TooltipTitle_RESID 38
#define actOpenArchive_SmallImages_RESID 39
#define actOpenArchive_LargeImages_RESID 40
#define actPrestations 15 
#define actPrestations_LabelTitle_RESID 41
#define actPrestations_TooltipTitle_RESID 42
#define actPrestations_TooltipDescription_RESID 43
#define actPrestations_SmallImages_RESID 44
#define actPrestations_LargeImages_RESID 45
#define actProduits 14 
#define actProduits_LabelTitle_RESID 46
#define actProduits_TooltipTitle_RESID 47
#define actProduits_TooltipDescription_RESID 48
#define actProduits_SmallImages_RESID 49
#define actProduits_LargeImages_RESID 50
#define actQuitter 13 
#define actQuitter_LabelTitle_RESID 51
#define actQuitter_TooltipTitle_RESID 52
#define actQuitter_TooltipDescription_RESID 53
#define actQuitter_SmallImages_RESID 54
#define actQuitter_LargeImages_RESID 55
#define actRognage 23 
#define actRognage_LabelTitle_RESID 56
#define actRognage_TooltipTitle_RESID 57
#define actRognage_TooltipDescription_RESID 58
#define actSaveArchive 12 
#define actSaveArchive_LabelTitle_RESID 59
#define actSaveArchive_TooltipTitle_RESID 60
#define actSaveArchive_SmallImages_RESID 61
#define actSaveArchive_LargeImages_RESID 62
#define actSites 25 
#define actSites_LabelTitle_RESID 63
#define actSites_TooltipTitle_RESID 64
#define actSites_TooltipDescription_RESID 65
#define actSites_SmallImages_RESID 66
#define actSites_LargeImages_RESID 67
#define actTypesSItes 28 
#define actTypesSItes_LabelTitle_RESID 68
#define actTypesSItes_TooltipTitle_RESID 69
#define actTypesSItes_SmallImages_RESID 70
#define actTypesSItes_LargeImages_RESID 71
#define actVehicules 31 
#define actVehicules_LabelTitle_RESID 72
#define actVehicules_TooltipTitle_RESID 73
#define actVehicules_TooltipDescription_RESID 74
#define actVehicules_SmallImages_RESID 75
#define actVehicules_LargeImages_RESID 76
#define cmdRecentItems 19 
#define cmdRecentItems_LabelTitle_RESID 77
#define grpBdd 35 
#define grpBdd_LabelTitle_RESID 60013
#define grpCatalogues 17 
#define grpCatalogues_LabelTitle_RESID 78
#define grpProduits 7 
#define grpProduits_LabelTitle_RESID 79
#define grpProduits_SmallImages_RESID 80
#define grpProduits_LargeImages_RESID 81
#define grpSites 8 
#define grpSites_LabelTitle_RESID 82
#define grpVacations 18 
#define grpVacations_LabelTitle_RESID 83
#define grpVehicules 9 
#define grpVehicules_LabelTitle_RESID 84
#define grpZonage 16 
#define grpZonage_LabelTitle_RESID 85
#define tabCartographie 32 
#define tabCartographie_LabelTitle_RESID 86
#define tabData 4 
#define tabData_LabelTitle_RESID 87
#define tabEconomic 6 
#define tabEconomic_LabelTitle_RESID 88
#define tabOperations 33 
#define tabOperations_LabelTitle_RESID 89
#define tabOutils 34 
#define tabOutils_LabelTitle_RESID 60014
#define tabParametres 30 
#define tabParametres_LabelTitle_RESID 90
#define InternalCmd2_LabelTitle_RESID 60015
#define InternalCmd6_LabelTitle_RESID 60016
